headers = [
    'Record Type',
    'Account', 
    'Symbol',
    'Daily Interest by Symbol',
    'PL Change',
    'GL Change',
    'Todays Equity',
    'TD Balance',
    'Long Stock MV',
    'Short Stock MV',
    'Long Option MV',
    'Short Option MV',
    'Long Bond MV',
    'Short Bond MV',
    'Pend Div Debit',
    'Pend Div Credit',
    'Pend Div Debit Ex-Date',
    'Pend Div Credit Ex-date',
    'Net TF Fees',
    'Net Commission',
    'Daily Interest',
    'MTD Interest',
    'Daily SSR Total',
    'MTD SSR Total',
    'CM Total Equity',
    'CM Commission',
    'CM Clmg & Exch Fees',
    'CM NFA Fee',
    'CM Gross PL',
    'CM Ending Balance',
    'E1Y Commission',
    'E1Y Commissions - Stock',
    'E1Y Commissions - Options', 
    'E1Y Commissions - Bonds',
    'E1Y Execution Fees',
    'E1Y Exec. Fees - Stocks',
    'E1Y Exec. Fees - Options',
    'E1Y Exec. Fees - Bonds',
    'E1Y SEC Fees',
    'E1Y SEC Fees Stocks',
    'E1Y SEC Fees Options',
    'E1Y SEC Fees Bonds',
    'E1Y Exch. Fees ',
    'E1Y Exch. Fees Stock',
    'E1Y Exch. Fees Options',
    'E1Y Exch. Fees Bonds',
    'E1YOff Floor Comm.',
    'OCC Fees',
    'Options Daily P&L',
    'Options MTD P&L',
    'Options YTD P&L',
    'Stocks Daily P&L',
    'Stocks MTD P&L',
    'Stocks YTD P&L',
    'Bond Accrued Interest',
    'Business Date',
    'Create Date',
    'Create Time'
    ]

div_headers = [
   'Record ID',
   'Record#', 
   'Business Date',
   'Reference #',
   'Account #',
   'Security Type',
   'CUSIP #',
   'ISIN #',
   'SEDOL #',
   'SYMBOL',
   'Security Description',
   'B/S',
   'QTY',
   'Debt Credit Code',
   'Amount',
   'Type of Entry',
   'Origin Code',
   'Memo code',
   'Symbol 21'
]
