div_headers = ['',
               'Row',
               'Date',
               '',
               'BAML Account',
               '',
               'CUSIP',
               '',
               '',
               '',
               'Description',
               'Buy/Sell',
               'Quantity',
               'Debit/Credit',
               'Amount',
               'Dividend Type',
               'Transaction Category',
               '',
               'Symbol']